AWSTemplateFormatVersion: "2010-09-09"
Description: JAN12 - ALB (HTTP only) using existing VPC/Subnets from Jan10

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  AlbSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet in AZ-A (for ALB)

  AlbSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet in AZ-B (for ALB)

  WebSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for the web instance (use PUBLIC subnet if no NAT; PRIVATE subnet if you have NAT)

  MyIpCidr:
    Type: String
    Description: Your public IP in CIDR format (e.g., 1.2.3.4/32). Used for optional SSH.

  InstanceType:
    Type: String
    Default: t3.micro

  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from internet to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from ALB; optional SSH from My IP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref AlbSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIpCidr

  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      SubnetId: !Ref WebSubnetId
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xe
          yum update -y
          yum install -y nginx
          systemctl enable nginx
          echo "JAN12 ALB TEST OK - $(hostname)" > /usr/share/nginx/html/index.html
          systemctl start nginx

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Name: jan12-tg
      Port: 80
      Protocol: HTTP
      TargetType: instance
      Targets:
        - Id: !Ref WebInstance
          Port: 80
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      Matcher:
        HttpCode: "200-399"

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: jan12-alb
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref AlbSubnet1
        - !Ref AlbSubnet2
      SecurityGroups:
        - !Ref AlbSecurityGroup

  ListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  AlbDnsName:
    Description: Open in browser (http://...)
    Value: !GetAtt LoadBalancer.DNSName

  WebInstanceId:
    Value: !Ref WebInstance
